# 演習問題

## 3.1

自明。

## 3.2

In [1]:
using LinearAlgebra

function P(m, i, j)
    A = diagm(0 => ones(m))
    A[i, :], A[j, :] = A[j, :], A[i, :]
    return A
end

function Q(m, i, c)
    A = diagm(0 => ones(m))
    A[i, i] = c
    return A
end

function R(m, i, j, c)
    A = diagm(0 => ones(m))
    A[i, j] = c
    return A
end

R (generic function with 1 method)

In [2]:
A = [1 2 2 6; 3 6 8 24; 2 4 4 12]

3×4 Matrix{Int64}:
 1  2  2   6
 3  6  8  24
 2  4  4  12

In [3]:
A₁ = R(3, 2, 1, -3) * A

3×4 Matrix{Float64}:
 1.0  2.0  2.0   6.0
 0.0  0.0  2.0   6.0
 2.0  4.0  4.0  12.0

In [4]:
A₂ = R(3, 3, 1, -2) * A₁

3×4 Matrix{Float64}:
 1.0  2.0  2.0  6.0
 0.0  0.0  2.0  6.0
 0.0  0.0  0.0  0.0

In [5]:
A₃ = Q(3, 2, 1//2) * A₂

3×4 Matrix{Float64}:
 1.0  2.0  2.0  6.0
 0.0  0.0  1.0  3.0
 0.0  0.0  0.0  0.0

In [6]:
A₄ = R(3, 1, 2, -2) * A₃

3×4 Matrix{Float64}:
 1.0  2.0  0.0  0.0
 0.0  0.0  1.0  3.0
 0.0  0.0  0.0  0.0

## 3.3

In [7]:
using SymPy

In [8]:
A = Sym[1 2 2 6; 3 6 8 24; 2 4 4 12]

3×4 Matrix{Sym}:
 1  2  2   6
 3  6  8  24
 2  4  4  12

In [9]:
A.rref()

(Sym{PyCall.PyObject}[1 2 0 0; 0 0 1 3; 0 0 0 0], (0, 2))

In [10]:
rank(A)

2

In [11]:
r = Int(rank(A))
A[1:r, :]

2×4 Matrix{Sym}:
 1  2  2   6
 3  6  8  24

In [23]:
function CR(A)
    # A.rref() から行列部分を取得
    E = A.rref()[1]
    
    # ランクの取得
    r = Int(rank(A))
    
    # ピボット列のインデックスを取得（ここまでは型を気にせず進める）
    col = [findfirst(!iszero, E[i, :]) for i in 1:r]
    
    # --- ここで型を強制的に Matrix{Sym} に変換する ---
    # Array{Sym}(...) で Julia 側の Sym 型行列として再構成します
    C = Array{Sym}(A[:, col])
    R = Array{Sym}(E[1:r, :])
    
    return C, R
end

CR (generic function with 1 method)

In [24]:
C, R₁ = CR(A)

(Sym[1 2; 3 8; 2 4], Sym[1 2 0 0; 0 0 1 3])

In [25]:
C

3×2 Matrix{Sym}:
 1  2
 3  8
 2  4

In [26]:
R₁

2×4 Matrix{Sym}:
 1  2  0  0
 0  0  1  3

In [27]:
A == C * R₁

true

## 3.4

(2) (1)より、$\operatorname{rank}(A^T)\leq\operatorname{rank}\left[\begin{array}{c|c}A^T & B^T\end{array}\right]\leq\operatorname{rank}(A^T)+\operatorname{rank}(B^T)$である。  
定理3.3.7より、$\operatorname{rank}(A^T)=\operatorname{rank}(A), \operatorname{rank}(B^T)=\operatorname{rank}(B)$であり、$\operatorname{rank}\left[\begin{array}{c|c}A^T & B^T\end{array}\right]=\operatorname{rank}\left[\begin{array}{c}A \\B\end{array}\right]$である。
以上から(2)が成り立つ。

(3) (2)および(1)により、$\operatorname{rank}\left[
\begin{array}{cc}
A & B \\
C & D
\end{array}
\right]\geq\operatorname{rank}\left[\begin{array}{c|c}A & B\end{array}\right]\geq\operatorname{rank}(A)$である。

(4) 明らか。

## 3.5

$A,B$ は $3$ 次正方行列の中から探すことにする。  
$\operatorname{rank}(A)=3$ or $\operatorname{rank}(B)=3$ のときには、定理3.3.8より、 $\operatorname{rank}(AB)=\operatorname{rank}(BA)=3$ になってしまう。  
$\operatorname{rank}(A)\leq 1$ or $\operatorname{rank}(B)\leq 1$ のときには、定理3.3.10より、 $\operatorname{rank}(AB)\leq 1$ and $\operatorname{rank}(BA)\leq 1$ となってしまい、よりつまらない例しか探せない。   
そこで、 $\operatorname{rank}(A)=\operatorname{rank}(B)=2$ となるような行列で、 $\operatorname{rank}(AB)=1$ and $\operatorname{rank}(BA)=2$ となるようなものを探すことにする。  

In [43]:
A = [1 0 0; 0 1 0; 1 1 0]

3×3 Matrix{Int64}:
 1  0  0
 0  1  0
 1  1  0

In [44]:
B = [1 0 0; 1 0 0; 0 1 0]

3×3 Matrix{Int64}:
 1  0  0
 1  0  0
 0  1  0

In [45]:
println(rank(A*B))
println(rank(B*A))

1
2
