# 演習問題

## 3.1

自明。

## 3.2

In [1]:
using LinearAlgebra

function P(m, i, j)
    A = diagm(0 => ones(m))
    A[i, :], A[j, :] = A[j, :], A[i, :]
    return A
end

function Q(m, i, c)
    A = diagm(0 => ones(m))
    A[i, i] = c
    return A
end

function R(m, i, j, c)
    A = diagm(0 => ones(m))
    A[i, j] = c
    return A
end

R (generic function with 1 method)

In [2]:
A = [1 2 2 6; 3 6 8 24; 2 4 4 12]

3×4 Matrix{Int64}:
 1  2  2   6
 3  6  8  24
 2  4  4  12

In [3]:
A₁ = R(3, 2, 1, -3) * A

3×4 Matrix{Float64}:
 1.0  2.0  2.0   6.0
 0.0  0.0  2.0   6.0
 2.0  4.0  4.0  12.0

In [4]:
A₂ = R(3, 3, 1, -2) * A₁

3×4 Matrix{Float64}:
 1.0  2.0  2.0  6.0
 0.0  0.0  2.0  6.0
 0.0  0.0  0.0  0.0

In [5]:
A₃ = Q(3, 2, 1//2) * A₂

3×4 Matrix{Float64}:
 1.0  2.0  2.0  6.0
 0.0  0.0  1.0  3.0
 0.0  0.0  0.0  0.0

In [6]:
A₄ = R(3, 1, 2, -2) * A₃

3×4 Matrix{Float64}:
 1.0  2.0  0.0  0.0
 0.0  0.0  1.0  3.0
 0.0  0.0  0.0  0.0

## 3.3

In [7]:
using SymPy

In [8]:
A = Sym[1 2 2 6; 3 6 8 24; 2 4 4 12]

3×4 Matrix{Sym}:
 1  2  2   6
 3  6  8  24
 2  4  4  12

In [9]:
A.rref()

(Sym{PyCall.PyObject}[1 2 0 0; 0 0 1 3; 0 0 0 0], (0, 2))

In [10]:
rank(A)

2

In [11]:
r = Int(rank(A))
A[1:r, :]

2×4 Matrix{Sym}:
 1  2  2   6
 3  6  8  24

In [23]:
function CR(A)
    # A.rref() から行列部分を取得
    E = A.rref()[1]
    
    # ランクの取得
    r = Int(rank(A))
    
    # ピボット列のインデックスを取得（ここまでは型を気にせず進める）
    col = [findfirst(!iszero, E[i, :]) for i in 1:r]
    
    # --- ここで型を強制的に Matrix{Sym} に変換する ---
    # Array{Sym}(...) で Julia 側の Sym 型行列として再構成します
    C = Array{Sym}(A[:, col])
    R = Array{Sym}(E[1:r, :])
    
    return C, R
end

CR (generic function with 1 method)

In [24]:
C, R₁ = CR(A)

(Sym[1 2; 3 8; 2 4], Sym[1 2 0 0; 0 0 1 3])

In [25]:
C

3×2 Matrix{Sym}:
 1  2
 3  8
 2  4

In [26]:
R₁

2×4 Matrix{Sym}:
 1  2  0  0
 0  0  1  3

In [27]:
A == C * R₁

true

## 3.4

(2) (1)より、$\operatorname{rank}(A^T)\leq\operatorname{rank}\left[\begin{array}{c|c}A^T & B^T\end{array}\right]\leq\operatorname{rank}(A^T)+\operatorname{rank}(B^T)$である。  
定理3.3.7より、$\operatorname{rank}(A^T)=\operatorname{rank}(A), \operatorname{rank}(B^T)=\operatorname{rank}(B)$であり、$\operatorname{rank}\left[\begin{array}{c|c}A^T & B^T\end{array}\right]=\operatorname{rank}\left[\begin{array}{c}A \\B\end{array}\right]$である。
以上から(2)が成り立つ。

(3) (2)および(1)により、$\operatorname{rank}\left[
\begin{array}{cc}
A & B \\
C & D
\end{array}
\right]\geq\operatorname{rank}\left[\begin{array}{c|c}A & B\end{array}\right]\geq\operatorname{rank}(A)$である。

(4) 明らか。

## 3.5

$A,B$ は $3$ 次正方行列の中から探すことにする。  
$\operatorname{rank}(A)=3$ or $\operatorname{rank}(B)=3$ のときには、定理3.3.8より、 $\operatorname{rank}(AB)=\operatorname{rank}(BA)=3$ になってしまう。  
$\operatorname{rank}(A)\leq 1$ or $\operatorname{rank}(B)\leq 1$ のときには、定理3.3.10より、 $\operatorname{rank}(AB)\leq 1$ and $\operatorname{rank}(BA)\leq 1$ となってしまい、最もつまらない例しか探せない。   
少しはましな例を探すため、 $\operatorname{rank}(A)=\operatorname{rank}(B)=2$ となるような行列で、 $\operatorname{rank}(AB)=1$ and $\operatorname{rank}(BA)=2$ となるようなものを探すことにする。  

In [43]:
A = [1 0 0; 0 1 0; 1 1 0]

3×3 Matrix{Int64}:
 1  0  0
 0  1  0
 1  1  0

In [44]:
B = [1 0 0; 1 0 0; 0 1 0]

3×3 Matrix{Int64}:
 1  0  0
 1  0  0
 0  1  0

In [45]:
println(rank(A*B))
println(rank(B*A))

1
2


## 3.6

$A$ を $m\times n$ 行列とする。  
$B$ を $p\times q$ 行列とする。  
$A=\begin{bmatrix}
   a_1 & a_2 & \cdots & a_n
\end{bmatrix},
B=\begin{bmatrix}
   b_1 & b_2 & \cdots & b_q
\end{bmatrix}$ と書く。  
$A\otimes B =
\begin{bmatrix}
a_1\otimes b_1 & a_1\otimes b_2 & \cdots & a_1\otimes b_q & a_2\otimes b_1 & a_2\otimes b_2 & \cdots & a_2\otimes b_q & \cdots & a_n\otimes b_1 & a_n\otimes b_2 \cdots & a_n\otimes b_q 
\end{bmatrix}$ である。  
$\operatorname{rank}(A)=r, \operatorname{rank}(B)=s$ とする。  
$a_{i_1},\dots,a_{i_r}$, $b_{j_1},\dots,b_{j_s}$ をそれぞれ一次独立な列ベクトルの列とする。  
$a_{i_1}\otimes b_{j_1}, a_{i_1}\otimes b_{j_2}, \cdots, a_{i_1}\otimes b_{j_s}, a_{i_2}\otimes b_{j_1}, a_{i_2}\otimes b_{j_2}, \cdots, a_{i_2}\otimes b_{j_s}, \cdots, a_{i_r}\otimes b_{j_1}, a_{i_r}\otimes b_{j_2}, \cdots, a_{i_r}\otimes b_{j_s}$ が一次独立であることを以下で示す。  
$c_{11} a_{i_1}\otimes b_{j_1} + c_{12} a_{i_1}\otimes b_{j_2} + \cdots + c_{1s} a_{i_1}\otimes b_{j_s} + c_{21} a_{i_2}\otimes b_{j_1} + c_{22} a_{i_2}\otimes b_{j_2} + \cdots + c_{2s} a_{i_2}\otimes b_{j_s} + \cdots + c_{r1} a_{i_r}\otimes b_{j_1} + c_{r2} a_{i_r}\otimes b_{j_2} + \cdots + c_{rs} a_{i_r}\otimes b_{j_s} = 0$ とする。  
p64 定理2.4.5を使って整理する。  
$a_{i_1}\otimes (c_{11} b_{j_1} + c_{12} b_{j_2} + \cdots + c_{1s} b_{j_s}) +
a_{i_2}\otimes (c_{21} b_{j_1} + c_{22} b_{j_2} + \cdots + c_{2s} b_{j_s}) + 
\cdots
a_{i_r}\otimes (c_{r1} b_{j_1} + c_{r2} b_{j_2} + \cdots + c_{rs} b_{j_s}) = 0$ である。  
$a_{i_1}, \dots, a_{i_r}$ が一次独立であるとき、 $\sum_k a_{i_k}\otimes d_{i_k} = 0$ ならば $d_{i_k} = 0$ が成り立つことは $\sum_k a_{i_k}\otimes d_{i_k}$ を具体的に書いてみれば容易にわかる。  
よって、 $c_{k1} b_{j_1} + c_{k2} b_{j_2} + \cdots + c_{ks} b_{j_s}=0$ である。  
$b_{j_1},\dots,b_{j_s}$ は一次独立な列なので、 $c_{ij}=0$ である。  
よって、 $a_{i_1}\otimes b_{j_1}, a_{i_1}\otimes b_{j_2}, \cdots, a_{i_1}\otimes b_{j_s}, a_{i_2}\otimes b_{j_1}, a_{i_2}\otimes b_{j_2}, \cdots, a_{i_2}\otimes b_{j_s}, \cdots, a_{i_1}\otimes b_{j_s}, a_{i_2}\otimes b_{j_s}, \cdots, a_{i_r}\otimes b_{j_s}$ は一次独立である。   
$a_i$ を $A$ の任意の列ベクトルとする。  
$b_j$ を $B$ の任意の列ベクトルとする。  
$a_i = \alpha_1 a_{i_1} + \cdots + \alpha_r a_{i_r}$ と書ける。  
$b_j = \beta_1 a_{j_1} + \cdots + \beta_s a_{j_s}$ と書ける。  
\begin{align*}
a_i\otimes b_j&=(\alpha_1 a_{i_1} + \cdots + \alpha_r a_{i_r})\otimes(\beta_1 a_{j_1} + \cdots + \beta_s a_{j_s})\\
&=\alpha_1\beta_1 (a_{i_1}\otimes b_{j_1}) + \alpha_1\beta_1 (a_{i_1}\otimes b_{j_2}) + \cdots + \alpha_1\beta_s (a_{i_1}\otimes b_{j_s}) + \alpha_2\beta_1 (a_{i_2}\otimes b_{j_1}) + \alpha_2\beta_2 (a_{i_2}\otimes b_{j_2}) + \cdots + \alpha_2\beta_s (a_{i_2}\otimes b_{j_s}) + \cdots + \alpha_r\beta_1 (a_{i_r}\otimes b_{j_1}) + \alpha_r\beta_2 (a_{i_r}\otimes b_{j_2}) + \cdots + \alpha_r\beta_s (a_{i_r}\otimes b_{j_s}) = 0
\end{align*}
である。  
よって、 $\operatorname{rank}(A\otimes B)=rs$ である。 